# Generated by Django 5.2.7 on 2025-10-28 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_uniform_color', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '팀',
                'verbose_name_plural': '팀들',
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('player_number', models.IntegerField()),
                ('player_main_position', models.CharField(choices=[('CF', 'center forward'), ('SS', 'second striker'), ('LWF', 'left wing forward'), ('AM', 'attack midfielder'), ('RWF', 'right wing forward'), ('LM', 'left midfielder'), ('CM', 'center midfielder'), ('RM', 'right midfielder'), ('LWB', 'left wing back'), ('DM', 'defend midfielder'), ('RWB', 'right wing back'), ('LB', 'left back'), ('CB', 'center back'), ('RB', 'right back'), ('GK', 'goal keeper')], max_length=10)),
                ('player_sub_position', models.CharField(blank=True, choices=[('CF', 'center forward'), ('SS', 'second striker'), ('LWF', 'left wing forward'), ('AM', 'attack midfielder'), ('RWF', 'right wing forward'), ('LM', 'left midfielder'), ('CM', 'center midfielder'), ('RM', 'right midfielder'), ('LWB', 'left wing back'), ('DM', 'defend midfielder'), ('RWB', 'right wing back'), ('LB', 'left back'), ('CB', 'center back'), ('RB', 'right back'), ('GK', 'goal keeper')], max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team')),
            ],
            options={
                'verbose_name': '선수',
                'verbose_name_plural': '선수들',
                'db_table': 'players',
                'constraints': [models.UniqueConstraint(fields=('team', 'player_number'), name='unique_player_number_per_team')],
            },
        ),
    ]
