# Generated by Django 5.2.7 on 2025-11-07 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50, verbose_name='팀명')),
                ('description', models.TextField(blank=True, verbose_name='팀 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('team_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='팀 생성자')),
            ],
            options={
                'verbose_name': '팀',
                'verbose_name_plural': '팀들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='선수이름')),
                ('number', models.PositiveIntegerField(verbose_name='등번호')),
                ('position', models.CharField(choices=[('GK', '골키퍼'), ('LB', '레프트백'), ('CB', '센터백'), ('RB', '라이트백'), ('LWB', '레프트 윙백'), ('DM', '수비형 미드필더'), ('RWB', '라이트 윙백'), ('LM', '레프트 미드필더'), ('CM', '센터 미드필더'), ('RM', '라이트 미드필더'), ('LW', '레프트 윙'), ('AM', '공격형 미드필더'), ('RW', '라이트 윙'), ('ST', '스트라이커')], max_length=3, verbose_name='포지션')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team', verbose_name='소속팀')),
            ],
            options={
                'verbose_name': '선수',
                'verbose_name_plural': '선수들',
                'ordering': ['number'],
                'unique_together': {('team', 'number')},
            },
        ),
    ]
